In [ ]:
print("Notebook is working! 🎉")

In [ ]:
#creating numpy/n-d arrays
import numpy as np

In [ ]:
arr13=np.arange(24)
arr13

In [ ]:
type(arr1)

In [ ]:
arr2=np.array([[1,2,3] ,[6,7,8]])
arr2

In [ ]:
arr1=np.array([1,2,3,4,5])
arr1

In [ ]:
arr3=np.zeros((2,3))
arr3

In [ ]:
arr4=np.ones((3,3))
arr4

In [ ]:
arr5=np.empty((2,3))
arr5

In [ ]:
arr6=np.random((2,3))
arr6

In [ ]:
arr7=np.identity(5)
arr7

In [ ]:
arr8=np.arange(100)
arr8

In [ ]:
arr9=np.linspace(10,15,10)
arr9

In [ ]:
arr10=arr8.copy()
arr10

In [ ]:
arr1.shape

In [ ]:
arr8.shape

In [ ]:
arr11=np.array([[[2,3],[4,5]],[[6,7],[8,9]]])
arr11

In [ ]:
arr11.shape

In [ ]:
arr11.ndim

In [ ]:
arr2

In [ ]:
arr2.ndim

In [ ]:
arr2.size

In [ ]:
arr2.itemsize

In [ ]:
arr1.itemsize

In [ ]:
arr1

In [ ]:
arr10.dtype

In [ ]:
arr9.astype('int')

In [3]:
import sys
lista=range(100)
arr12=np.arange(100)
print(sys.getsizeof(87)*len(lista))


2800


In [4]:
print(arr12.itemsize*arr12.size)

800


In [46]:
import time
x = range(10000000)
y = range(10000000 , 20000000)
start_time = time.time()
c = [(x,y) for x,y in zip(x,y)]
print(time.time() - start_time)

3.9598608016967773


In [49]:
import time
x = np.arange(10000)
y = np.arange(10000 , 20000)
start_time = time.time()
c = x+y
print(time.time() - start_time)

9.080050468444824


In [50]:
arr13=np.arange(24)
arr13

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [51]:
arr13=np.arange(24).reshape(3,8)
arr13

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [52]:
arr13=np.arange(100).reshape(10,10)
arr13

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [59]:
arr13[2]

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [60]:
arr13[1:2]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [61]:
arr13[0:2]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [62]:
arr13[::3]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [63]:
arr13[3::]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [64]:
arr13[1:1]

array([], shape=(0, 10), dtype=int64)

In [66]:
arr13[1:3]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [67]:
arr13

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [72]:
arr13[0:0][10:3]

array([], shape=(0, 10), dtype=int64)

In [74]:
arr13[:,1]

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [76]:
arr13[:,9]

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])

In [77]:
arr13[:,1:3]

array([[ 1,  2],
       [11, 12],
       [21, 22],
       [31, 32],
       [41, 42],
       [51, 52],
       [61, 62],
       [71, 72],
       [81, 82],
       [91, 92]])

In [78]:
arr13

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [87]:
arr13[8:10,8:10]

array([[88, 89],
       [98, 99]])

In [88]:
#iteration
arr13

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [91]:
for i in arr13:
      print(i)   

[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]
[20 21 22 23 24 25 26 27 28 29]
[30 31 32 33 34 35 36 37 38 39]
[40 41 42 43 44 45 46 47 48 49]
[50 51 52 53 54 55 56 57 58 59]
[60 61 62 63 64 65 66 67 68 69]
[70 71 72 73 74 75 76 77 78 79]
[80 81 82 83 84 85 86 87 88 89]
[90 91 92 93 94 95 96 97 98 99]


In [92]:
for i in np.nditer(arr13):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99


In [93]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,10])
arr1-arr2

array([-5, -5, -5, -5, -5])

In [94]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,10])
arr1*arr2

array([ 6, 14, 24, 36, 50])

In [95]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,10])
arr1+arr2

array([ 7,  9, 11, 13, 15])

In [96]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,10])
arr1/arr2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [97]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,10])
arr1%arr2

array([1, 2, 3, 4, 5])

In [98]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,10])
arr1//arr2

array([0, 0, 0, 0, 0])

In [99]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,10])
arr1**arr2

array([      1,     128,    6561,  262144, 9765625])

In [112]:
arr3=np.arange(6).reshape(3,2)
arr4=np.arange(18,24).reshape(2,3)
arr3.dot(arr4)

array([[ 21,  22,  23],
       [ 99, 104, 109],
       [177, 186, 195]])

In [119]:
arr3=np.arange(18).reshape(6,3)
arr4=np.arange(18,36).reshape(3,6)
arr3.dot(arr4)

array([[  84,   87,   90,   93,   96,   99],
       [ 300,  312,  324,  336,  348,  360],
       [ 516,  537,  558,  579,  600,  621],
       [ 732,  762,  792,  822,  852,  882],
       [ 948,  987, 1026, 1065, 1104, 1143],
       [1164, 1212, 1260, 1308, 1356, 1404]])

In [121]:
arr3=np.arange(6).reshape(2,3)
arr4=np.arange(6,12).reshape(3,2)
arr3.dot(arr4)

array([[ 28,  31],
       [100, 112]])

In [124]:
arr5=np.arange(6).reshape(2,3)
arr5

array([[0, 1, 2],
       [3, 4, 5]])

In [126]:
arr1
arr2

array([ 6,  7,  8,  9, 10])

In [128]:
arr1.dot(arr2)

np.int64(130)

In [129]:
arr1.dot(arr3)

ValueError: shapes (5,) and (2,3) not aligned: 5 (dim 0) != 2 (dim 0)

In [134]:
arr3.max()

np.int64(5)

In [135]:
arr4.min()

np.int64(6)

In [136]:
arr3

array([[0, 1, 2],
       [3, 4, 5]])

In [138]:
arr3.min(axis=0)

array([0, 1, 2])

In [139]:
arr3.min(axis=1)

array([0, 3])

In [140]:
arr3.sum()

np.int64(15)

In [141]:
arr3.sum(axis=0)

array([3, 5, 7])

In [142]:
arr3.sum(axis=1)

array([ 3, 12])

In [143]:
arr3.mean()

np.float64(2.5)

In [144]:
arr3.std()

np.float64(1.707825127659933)

In [145]:
np.sin(arr3)

array([[ 0.        ,  0.84147098,  0.90929743],
       [ 0.14112001, -0.7568025 , -0.95892427]])

In [146]:
np.median(arr3)

np.float64(2.5)

In [117]:

arrA = np.arange(5).reshape(1, 5)
arrB = np.arange(5, 10).reshape(5, 1)
arrA.dot(arrB)

array([[80]])

In [118]:
#scaler methods
arr1*2

array([ 2,  4,  6,  8, 10])

In [101]:
arr2<3

array([False, False, False, False, False])

In [102]:
arr1<2

array([ True, False, False, False, False])

In [103]:
arr1<6

array([ True,  True,  True,  True,  True])

In [55]:
arr1=np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [58]:
arr1[2:4]

array([3, 4])

In [ ]:
name = input("enter the name")
print("HAPPY BIRTHDAY TO YOU",name)


In [ ]:
print("bhawana")

# My First Mini Project

In [ ]:
i = 1
while i<=100:
    print("HAPPY BIRTHDAYTO YOU")

In [ ]:
# My First Mini Project
print("Notebook is working! 🎉")